riscv: Add missing asm/kernel.h header
Fixes the following compilation issue:

include/linux/kernel.h:5:10: fatal error: asm/kernel.h: No such file
or directory
    5 | #include "asm/kernel.h"

Tested-by: Alexandru Elisei <alexandru.elisei@arm.com>
Reviewed-by: Alexandru Elisei <alexandru.elisei@arm.com>
Signed-off-by: Dao Lu <daolu@rivosinc.com>
Reviewed-by: Anup Patel <anup@brainfault.org>
Fixes: 0febaae00bb6 ("Add cpumask functions")
Link: https://lore.kernel.org/r/20220524180030.1848992-1-daolu@rivosinc.com
Signed-off-by: Will Deacon <will@kernel.org>